### ISSUE TITLE
dynamic binding

### ISSUE THREAD

**Issue by NagarRahul** [knockout/knockout#2577]
Hi, I want to pass binding like that
       **data-bind="value: {{Building}}"
       data-bind="value: {{Building}}.{{Device}}.Temp"
       data-bind="value: {{Building}}.{{Device}}.{{Temp}}"
        data-bind="value: Building.Device.Temp"**

How we can handle these conditions and how we can create the dynamic model?
@haru01 @steveluscher @rampion @schinckel @aaronblohowiak @

**Comment by webketje** [comment]
```js
function Building(name, devices = []) {
  this.name = name;
  this.devices = devices;
}
function App(buildings, initialSelection) {
  this.buildings = buildings || [];
  this.current = {
    building: ko.observable(this.getBuildings(initialSelection.building))
  };
  this.current.device: ko.observable(this.getDevices(initialSelection.device)),
  this.current.temp: ko.observable(this.getTemps(initialSelection.temp));
}
App.prototype.getBuildings = function(index) {
  if (typeof index === 'number')  return this.buildings[index];
  return this.buildings;
};
App.prototype.getDevices = function(index) {
  const building = this.getBuildings(this.current.building());
  if (typeof index === 'number')  return building && building.devices[index];
  return building && building.devices;
};
App.prototype.getTemps = function(index) {
  const device = this.getDevices(this.current.device());
  if (typeof index === 'number')  return device && device.temps[index];
  return device && device.temps;
};

const initialSelection = { building: 0, device: 0, temp: 0 };

ko.applyBindings(new App(
  [
    new Building('Building 1', [
       { name: 'device0', temps: [15, 24, 13] },
       { name: 'device3', temps: [18, 29, 3] }
    ]),
    new Building('Building 2', [
       { name: 'device1', temps: [15, 24, 13] },
       { name: 'device2', temps: [18, 29, 3] }
    ]),
    new Building('Building 3', [
       { name: 'device5', temps: [15, 24, 13] },
       { name: 'device7', temps: [18, 29, 3] }
    ]),
  ], initialSelection), document.body);
```
```html
<select data-bind="value: current.building, options: getBuildings(), optionsText: 'name'"></select>
<select data-bind="value: current.device, options: getDevices(), optionsText: 'name'"></select>
<select data-bind="value: current.temp, options: getTemps()"></select>
```

**Comment by NagarRahul** [comment]
Thanks for the reply but this is not working. I have to try and I am getting this error.
![image](https://user-images.githubusercontent.com/42827466/134895814-3ec70e3b-a72e-41df-bbd9-64e895c10c27.png)

And one more thing I want to bind all there or maybe four data models with a single label.
like this-

    <label data-bind="value: {{Building}}.{{Device}}.{{Temp}}"></label>

 Building = "ABC";
 Building = "XYZ";
Device = "AHU";
Device = "HVAC";
Temp = "abc";
Temp= 12
Temp = 2.25

these parameters change according to the configuration.
Because I have a data with JSON like this- 

  {
    "Variable": "ABC.AHU.abc",
    "value": "574"
  }

So, I am finding the match and get the value for the Matching string.
Now the output after render the html like this-
<label data-bind="value: {{Building}}.{{Device}}.{{Temp}}">**574**</label>
@mbest @webketje @haru01 @steveluscher

**Comment by webketje** [comment]
@NagarRahul I've updated my snippet. The full name is in `fullId`. I didn't think Knockout wouldn't add prototype methods to the context, so I fixed that & a few typo's. If you have further questions, please ask on StackOverflow, this is not the place. And please close #2578

**Comment by NagarRahul** [comment]
Still getting this-
![image](https://user-images.githubusercontent.com/42827466/134913847-3cd6feb6-06f9-49da-96b9-c86bc3ab550b.png)

@webketje I have closed #2578 Ok next time I will ask on StackOverflow. Please help me to fix this error.

**Comment by NagarRahul** [comment]
![image](https://user-images.githubusercontent.com/42827466/134918256-11ad6512-973c-4710-b0af-7d8b2cc99215.png)

**building.devices  are return undefined**

**Comment by webketje** [comment]
Sorry, I didn't test the code, i reupdated it and it should work now

**Comment by NagarRahul** [comment]
@webketje 
**No it's not working**
![image](https://user-images.githubusercontent.com/42827466/134953401-0d9bc4cb-5d49-4075-ab53-0c7473e198a8.png)
![image](https://user-images.githubusercontent.com/42827466/134953463-3cdce420-0062-4ec7-a523-a5e3da600dfb.png)
